[package]
name = "yell-api"
version = "0.1.0"
authors = ["Eduardo L. Buratti <eburatti09@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
rmp-serde = "^0.14.0"
serde = { version = "^1.0.104", features = ["derive"] }

[profile.release]
opt-level = 'z'
lto = true
